id: P006728
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG6159
  title: ཇོ་ནང་རྗེ་བཙུན་ཐམས་ཅད་མཁྱེན་པ་ཏཱ་ར་ནཱ་ཐའི་བཀའ་འབུམ་དཔེ་བསྡུར་མའི་དཀར་ཆག
  author: ''
  volumes:
    1d74b99fa45c446fb85e17fcb47c1e36:
      image_group_id: I1KG8915
      title: ''
      volume_number: 1
      total_pages: 54
