id: I68B22489
legacy_id: P006728
ocr_import_info:
  bdrc_scan_id: W1KG6159
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T03:59:52'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T17:44:49.297039+00:00'
last_modified: 2022-09-01 01:44:53.765563
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG6159
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG6159
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཇོ་ནང་རྗེ་བཙུན་ཐམས་ཅད་མཁྱེན་པ་ཏཱ་ར་ནཱ་ཐའི་བཀའ་འབུམ་དཔེ་བསྡུར་མའི་དཀར་ཆག
statistics:
  ocr_word_mean_confidence_index: 0.6557736080982278
  ocr_word_median_confidence_index: 0.800000011920929
quality: null
bases:
  I1KG8915:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8915
      total_pages: 54
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG8915.txt
    statistics:
      ocr_word_median_confidence_index: 0.800000011920929
      ocr_word_mean_confidence_index: 0.6557736080982278
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
